apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ly2ebyk6f-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-dotnet-basic:34039237d0cb6931d4089ac684f835557f5398d3@sha256:248edd2ea0248af23bc2a308120b3d597874c99e270c403962e7bdf1b688a511
          name: container-image
